
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 17 21:01:54 CDT 2022
//----------------------------------------------------

package Interface;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 19;
  public static final int Or = 24;
  public static final int Fi = 7;
  public static final int Coma = 39;
  public static final int Until = 10;
  public static final int Llave_c = 34;
  public static final int Op_booleano = 30;
  public static final int Llave_a = 33;
  public static final int If = 6;
  public static final int T_dato = 4;
  public static final int Else = 8;
  public static final int Read = 20;
  public static final int Corchete_c = 36;
  public static final int Corchete_a = 35;
  public static final int Then = 25;
  public static final int Op_SR = 26;
  public static final int While = 11;
  public static final int Division = 17;
  public static final int Cadena = 5;
  public static final int Parentesis_c = 32;
  public static final int Parentesis_a = 31;
  public static final int For = 12;
  public static final int P_coma = 38;
  public static final int EOF = 0;
  public static final int Op_MD = 27;
  public static final int Not = 22;
  public static final int And = 23;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int Op_atribucion = 28;
  public static final int ERROR = 42;
  public static final int Do = 9;
  public static final int Op_logico = 18;
  public static final int Identificador = 40;
  public static final int Resta = 15;
  public static final int Multiplicacion = 16;
  public static final int Op_incremento = 29;
  public static final int Write = 21;
  public static final int Numero = 41;
  public static final int Program = 37;
  public static final int Suma = 14;
  public static final int Igual = 13;
  public static final int Comillas = 3;
}

